### ISSUE TITLE
Create Simulator

### ISSUE THREAD

**Issue by saliougaye** [ProjectWorkGruppo3/Simulator#1]
We want to create a Worker that simulate the smart bracelet.

**Comment by saliougaye** [comment]
Simulator Task:
- Authentication
    - Simulator request the credential of the user to start to send data
    - with the credential, make a login request to the API to retrieve a token
    - Use the token to make the POST requests
- Simulate Data
    - Simulate real data
    - Reset Steps Data
    - Cache data

**Comment by BaggioGiacomo** [comment]
Why are you instantiating more than one `Random` object? 🤔  Let's have a look [here](https://docs.microsoft.com/en-us/dotnet/api/system.random?view=net-6.0) !
